### PR TITLE
fix: Made the default bitmap image appear as preview.

### LINKED ISSUE #141: Display the default bitmap as preview when edittext is empty.
**Describe the feature you'd like**
If the edittext is empty and the preview button is clicked, the default bitmap should be shown as the preview as that is what is displayed on the real device.

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #141 

Changes: If the edit text is empty, the default image bitmap image is shown in the preview if clicked by the user.

GIF for the change:

ezgif com-video-to-gif (17)

### CODE REVIEW

**Comment by yashk2000** [comment]
@iamareebjamal @adityastic please review.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt [hunk 1]
```diff
@@ -112,13 +112,23 @@ class MessageActivity : AppCompatActivity() {
...
+                previewBadge.setValue(
+                        presenter.convertToPreview(content.text.toString()),
+                        marquee.isChecked,
+                        flash.isChecked,
+                        Speed.values()[speed.selectedItemPosition],
+                        Mode.values()[mode.selectedItemPosition]
+                )
+            } else {
+                previewBadge.setValue(
+                        Converters.convertDrawableToLEDHex((drawableRecyclerAdapter.getDefaultItem() as DrawableInfo).image) as java.util.ArrayList<String>,
```
Comment (adityastic) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]:
```suggestion
                        Converters.convertDrawableToLEDHex(resources.getDrawable(R.drawable.mix2)) as java.util.ArrayList<String>,
```

File: app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt [hunk 2]
```diff
@@ -45,6 +45,10 @@ class DrawableAdapter(private val context: Context, private val list: List<Drawa
         return if (selectedPosition == -1) -1 else list[selectedPosition]
     }
 
+    fun getDefaultItem(): Any {
```
Comment (adityastic) [inline app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]:
```suggestion
```

File: app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt [hunk 3]
```diff
@@ -45,6 +45,10 @@ class DrawableAdapter(private val context: Context, private val list: List<Drawa
...
+        return list[9]
```
Comment (adityastic) [inline app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]:
```suggestion
```

File: app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt [hunk 4]
```diff
@@ -45,6 +45,10 @@ class DrawableAdapter(private val context: Context, private val list: List<Drawa
...
+    }
```
Comment (adityastic) [inline app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]:
```suggestion
```

File: app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt [hunk 5]
```diff
@@ -45,6 +45,10 @@ class DrawableAdapter(private val context: Context, private val list: List<Drawa
...
+
```
Comment (adityastic) [inline app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]:
```suggestion
```

**Comment by yashk2000** [comment]
@adityastic I know the way you are suggesting it to be done. I did it that way because once the bitmaps can be sent to the device via Bluetooth, we could implement an option for the user to choose a default bitmap option. Currently, mix2 is the default. We could later provide the user with an option to choose his own bitmap. That's why I did it that way.

Please tell me your thoughts on this. I shall make the changes if needed.

**Comment by adityastic** [comment]
Oh, Ok bro. I get the idea now. Approved

File: app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt (hunk 2 above)
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]: Why not returning `DrawableInfo`?

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]: Yeah that would remove the type conversion as well

**Comment by yashk2000** [comment]
@iamareebjamal please review. I made `DrawableInfo` the return type of the function.

File: app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt [hunk 6]
```diff
@@ -45,6 +45,10 @@ class DrawableAdapter(private val context: Context, private val list: List<Drawa
         return if (selectedPosition == -1) -1 else list[selectedPosition]
     }
 
+    fun getDefaultItem(): DrawableInfo {
+        return list[9]
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]: 9 is a magic number. What if the list is modified or re-arranged or has less members or new members are added

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt (hunk 1 above)
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Remove cast

**Comment by yashk2000** [comment]
Please review @iamareebjamal

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt [hunk 7]
```diff
@@ -112,13 +112,23 @@ class MessageActivity : AppCompatActivity() {
...
+                previewBadge.setValue(
+                        presenter.convertToPreview(content.text.toString()),
+                        marquee.isChecked,
+                        flash.isChecked,
+                        Speed.values()[speed.selectedItemPosition],
+                        Mode.values()[mode.selectedItemPosition]
+                )
+            } else {
+                previewBadge.setValue(
+                        Converters.convertDrawableToLEDHex((drawableRecyclerAdapter.getDefaultItem()).image) as java.util.ArrayList<String>,
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: No casting

**Comment by iamareebjamal** [comment]
Please don't mark conversations as resolved. They'll be resolved automatically when you make the changes. You just resolved the conversation without removing the cast. This is very annoying for the reviewer

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt (hunk 7 above)
Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: @iamareebjamal I removed the redundant cast. Without this cast, there is an error.

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: This cast is needed.

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Why is it needed? What's the type of the object without casting?

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Without casting, it is a List<String> while an ArrayList<String> is needed.

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Return List from everywhere, never use implementations, always use abstractions.

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Sorry, I did not get this. A list is being returned from `convertDrawableToLEDHex`. In order to make it a bitmap to be displayed on the preview, it then has to be converted into an ArrayList.

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Wherever the function is returning `ArrayList` change it to `List` 

Whichever function is accepting `ArrayList` as argument, change it to `List`

There's a reason why List is an interface and ArrayList implements it. There are 3-4 List implementations. Why use the concrete type of ArrayList unless you are depending on its specific implementation which we are not. 

https://stackoverflow.com/questions/13552413/depend-on-abstractions-do-not-depend-on-concrete-classes

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Ok. Got it. Thanks for sharing this information.

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Made the changes. Please check if it is alright.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt [hunk 8]
```diff
@@ -112,19 +112,29 @@ class MessageActivity : AppCompatActivity() {
...
+                        Mode.FIXED
+                )
+            }
         }
 
         previewButtonDrawable.setOnClickListener {
             if (drawableRecyclerAdapter.getSelectedItem() != -1)
                 previewBadge.setValue(
-                        Converters.convertDrawableToLEDHex((drawableRecyclerAdapter.getSelectedItem() as DrawableInfo).image) as java.util.ArrayList<String>,
+                        Converters.convertDrawableToLEDHex((drawableRecyclerAdapter.getSelectedItem() as DrawableInfo).image),
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Remove cast

When casting anything, think about it 100 times that why is it needed. Is it actually needed or is it just an implementation error on my or previous developer's side.

Almost always, it will be the latter

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Here either -1(int) or the DrawableInfo will be returned. Hence without the cast, there will be an error.

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: How can an int or object can return from the same method?

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: OK. Please change the return type from Any to DrawableInfo

As I said earlier "just an implementation error on my or previous developer's side."

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Done.

**Comment by yashk2000** [comment]
Please review @iamareebjamal.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt [hunk 9]
```diff
@@ -112,19 +112,29 @@ class MessageActivity : AppCompatActivity() {
...
+                )
+            }
         }
 
         previewButtonDrawable.setOnClickListener {
-            if (drawableRecyclerAdapter.getSelectedItem() != -1)
+            if (drawableRecyclerAdapter.getSelectedItem() != null)
                 previewBadge.setValue(
-                        Converters.convertDrawableToLEDHex((drawableRecyclerAdapter.getSelectedItem() as DrawableInfo).image) as java.util.ArrayList<String>,
+                        Converters.convertDrawableToLEDHex((drawableRecyclerAdapter.getSelectedItem())!!.image),
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Never use !! in Kotlin

File: app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt [hunk 10]
```diff
@@ -41,8 +41,12 @@ class DrawableAdapter(private val context: Context, private val list: List<Drawa
         }
     }
 
-    fun getSelectedItem(): Any {
-        return if (selectedPosition == -1) -1 else list[selectedPosition]
+    fun getSelectedItem(): DrawableInfo? {
+        return if (selectedPosition == -1) null else list[selectedPosition]
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]: Return default item in case of -1

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]: @iamareebjamal if default item is returned, the preview will display it along with animation modes/speeds set by the user. But if preview is clicked without any parameter, the default item is to be shown with no animation, in fixed mode. I will return null and then check if the returned value is null, and then preview the default item with no animation. Is it alright that way?

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/adapter/DrawableAdapter.kt]: I have made the changes. Please tell if this way is alright?

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt (hunk 9 above)
Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Done.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt [hunk 11]
```diff
@@ -112,26 +112,43 @@ class MessageActivity : AppCompatActivity() {
...
-                        Converters.convertDrawableToLEDHex((drawableRecyclerAdapter.getSelectedItem() as DrawableInfo).image) as java.util.ArrayList<String>,
+                        Converters.convertDrawableToLEDHex(selectedItem.image),
                         marquee.isChecked,
                         flash.isChecked,
                         Speed.values()[speed.selectedItemPosition],
                         Mode.values()[mode.selectedItemPosition]
                 )
             else
-                Toast.makeText(this, getString(R.string.select_drawable), Toast.LENGTH_LONG).show()
+                previewBadge.setValue(
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Don't use default item, show toast as before. I asked for default item because you were using !!. Now it is fine

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: But if a parameter is left blank and preview is pressed, the default item should be displayed.
