### PR TITLE
fix: Prevented the app from crashing when a non-implemented character is entered.

### LINKED ISSUE #97: App crashes if a symbol which is not implemented is previewed.
**Describe the bug**
Some symbols such as cent, yen, or pounds are not yet implemented in the app symbols. When these symbols are typed and preview is pressed, the app crashes.

**To Reproduce**
Type the cent or yen symbols in the edit text and press preview. The app crashes.

**Expected behavior**
The app should not crash.

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Nokia 7 plus|
|Android Version|Android 9.0    |

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #97 

Changes: The app does not crash when a non-implemented character is previewed and a toast is shown.

GIF for the change:

ezgif com-video-to-gif (16)

### CODE REVIEW

**Comment by yashk2000** [comment]
@iamareebjamal @adityastic please review.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt [hunk 1]
```diff
@@ -113,7 +113,7 @@ class MessageActivity : AppCompatActivity() {
 
         previewButton.setOnClickListener {
             previewBadge.setValue(
-                    presenter.convertToPreview(if (!content.text.isEmpty()) content.text.toString() else " "),
+                    presenter.convertToPreview(if (!content.text.isEmpty()) content.text.toString() else " ", this),
```
Comment (adityastic) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Use context as the first parameter

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt [hunk 2]
```diff
@@ -32,10 +32,12 @@ class MessagePresenter {
         gattClient.stopClient()
     }
 
-    fun convertToPreview(data: String): ArrayList<String> {
+    fun convertToPreview(data: String, context: Context): ArrayList<String> {
```
Comment (adityastic) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: Same, Context First Parameter

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt [hunk 3]
```diff
@@ -32,10 +32,12 @@ class MessagePresenter {
...
     }
 
-    fun convertToPreview(data: String): ArrayList<String> {
+    fun convertToPreview(context: Context, data: String): ArrayList<String> {
         val list: ArrayList<String> = ArrayList()
         for (letter in data) {
-            list.add(DataToByteArrayConverter.CHAR_CODES.getValue(letter))
+            if (DataToByteArrayConverter.CHAR_CODES.containsKey(letter)) {
+                list.add(DataToByteArrayConverter.CHAR_CODES.getValue(letter))
+            } else Toast.makeText(context, R.string.character_not_found, Toast.LENGTH_SHORT).show()
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: Call method on view to show toast, don't use context in presenter

**Comment by yashk2000** [comment]
@liveHarshit is it alright now?

**Comment by yashk2000** [comment]
@iamareebjamal please review.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt [hunk 4]
```diff
@@ -32,12 +32,20 @@ class MessagePresenter {
         gattClient.stopClient()
     }
 
-    fun convertToPreview(data: String): ArrayList<String> {
+    fun convertToPreview(data: String): ArrayList<Any> {
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: Never use Any

**Comment by iamareebjamal** [comment]
You know the types, there are objects in Java, why would you return List of ANy type

**Comment by yashk2000** [comment]
@iamareebjamal please review.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt [hunk 5]
```diff
@@ -32,12 +32,17 @@ class MessagePresenter {
         gattClient.stopClient()
     }
 
-    fun convertToPreview(data: String): ArrayList<String> {
+    fun convertToPreview(data: String): Pair<Boolean, ArrayList<String>> {
+        var flag = true
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: When will flag be true/false

File: app/src/main/res/values/strings.xml [hunk 6]
```diff
@@ -26,4 +26,5 @@
     <string name="no_device_found">No device found. Please try again.</string>
     <string name="select_drawable_text">Select Drawable:</string>
     <string name="select_drawable">Please select Drawable to be previewed</string>
+    <string name="character_not_found">Some of the character/s entered cannot be displayed.</string>
```
Comment (iamareebjamal) [inline app/src/main/res/values/strings.xml]:
```suggestion
    <string name="character_not_found">Some of the character(s) entered cannot be displayed.</string>
```

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt (hunk 5 above)
Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: If the entire message contains valid characters, it will be true, else false.

**Comment by yashk2000** [comment]
@iamareebjamal changes made. Please review.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt (hunk 5 above)
Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: Then change name to valid, same above

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: Done.

File: app/src/main/res/values/strings.xml (hunk 6 above)
Comment (yashk2000) [reply app/src/main/res/values/strings.xml]: Done.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt [hunk 7]
```diff
@@ -32,12 +32,17 @@ class MessagePresenter {
...
-    fun convertToPreview(data: String): ArrayList<String> {
+    fun convertToPreview(data: String): Pair<Boolean, ArrayList<String>> {
+        var valid = true
         val list: ArrayList<String> = ArrayList()
         for (letter in data) {
-            list.add(DataToByteArrayConverter.CHAR_CODES.getValue(letter))
+            if (DataToByteArrayConverter.CHAR_CODES.containsKey(letter)) {
+                list.add(DataToByteArrayConverter.CHAR_CODES.getValue(letter))
+            } else {
+                valid = false
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: break here, once you know it's invalid, no need to continue

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: Done.

**Comment by yashk2000** [comment]
Please merge the pr if it is alright @iamareebjamal

**Comment by iamareebjamal** [comment]
Resolve conflicts

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt (hunk 7 above)
Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessagePresenter.kt]: @iamareebjamal we cannot break here. If the string is like "^efjjih" and "^" is the unimplemented character, rest of the characters also won't be displayed if break is placed in the else section. We have to allow the loop to run through the whole string such that the implemented characters can at least be displayed.

**Comment by yashk2000** [comment]
@iamareebjamal we cannot break here. If the string is like "^efjjih" and "^" is the unimplemented character, rest of the characters also won't be displayed if break is placed in the else section. We have to allow the loop to run through the whole string such that the implemented characters can at least be displayed.

I have resolved conflicts.
