### PR TITLE
fix: BLE connection only allowed one update without app restart

### LINKED ISSUE #1329: BLE Connection Allows Only One Update – Requires App Restart for Reconnect or Text Update
Description:

Currently, the app allows only a single successful text update to the connected badge via BLE. If the user
Tries to update the badge message again, or Attempts to connect to another device after disconnecting
the app fails to perform the operation. The only workaround is to restart the app, which resets the BLE state.

### PR DESCRIPTION
**Pull request by samruddhi-Rahegaonkar**
Fixes #1329 

## Changes 

- Fixed BLE reconnection issue where app required restart for each update
- Added pre-emptive disconnect before connecting to ensure clean BLE state
- Ensured FlutterBluePlus.stopScan() is properly called to prevent multiple connections
- Added minor delay between chunk writes for better stability

## Screenshots / Recordings  

**Checklist**: 
- [x] **No hard coding**: I have used resources from `constants.dart` without hard coding any value.
- [x] **No end of file edits**: No modifications done at end of resource files.
- [x] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [x] **Code analyzation**: My code passes analyzations run in _flutter analyze_ and tests run in _flutter test_.

## Summary by Sourcery

Fix BLE reconnection flow to allow repeated updates without restarting the app and refine dialog layout adjustments.

Bug Fixes:
- Allow BLE connections to reconnect without requiring an app restart after each update.

Enhancements:
- Preemptively disconnect the device before connecting and ensure FlutterBluePlus.stopScan() is called on success, error and finally to maintain a clean BLE state.
- Add minor delay between data chunk writes with improved logging for better stability.
- Refactor DeleteBadgeDialog layout by replacing fixed container sizing with responsive padding and adjusted spacings.

## Summary by Sourcery

Improve BLE reconnection flow to allow repeated firmware updates without restarting the app and refine the badge deletion dialog layout

Bug Fixes:
- Enable BLE reconnections without requiring an app restart after each update

Enhancements:
- Preemptively disconnect any existing BLE connection before attempting a new connect
- Ensure FlutterBluePlus.stopScan() is called on scan success, error, and cleanup for a clean BLE state
- Add a minor delay between BLE data chunk writes and improve logging for transfer stability
- Refactor DeleteBadgeDialog to use responsive padding and dynamic sizing instead of fixed dimensions

### CODE REVIEW

File: lib/bademagic_module/bluetooth/connect_state.dart [hunk 1]
```diff
@@ -12,7 +12,13 @@ class ConnectState extends RetryBleState {
   @override
   Future<BleState?> processState() async {
     bool connected = false;
-
+    try {
```
Comment (Jhalakupadhyay) [inline lib/bademagic_module/bluetooth/connect_state.dart]: did you verify this change because I dont think so that it will work by just disconnecting before. We already have this removeIfGone property ro handle this case.

Comment (samruddhi-Rahegaonkar) [reply lib/bademagic_module/bluetooth/connect_state.dart:15]: @Jhalakupadhyay could you verify this if you have an iphone ?

**Comment by samruddhi-Rahegaonkar** [comment]
@Jhalakupadhyay I have tested changes and it works on Mac OS there was issue previously with Mac too!

**Review by nope3472 — COMMENTED** [review]
Please update the new try-catch blocks to ensure all caught exceptions are properly logged instead of being silently ignored.

**Comment by samruddhi-Rahegaonkar** [comment]
@Jhalakupadhyay I have tested it on badge its working fine!

**Review by Jhalakupadhyay — APPROVED** [review]

**Comment by Jhalakupadhyay** [comment]
@samruddhi-Rahegaonkar update the branch and I will merge it

**Comment by hpdang** [comment]
@samruddhi-Rahegaonkar please update the branch

**Review by nope3472 — COMMENTED** [review]
This looks good just add
-Error Handling for Disconnects
-Ensure Disconnect After Write

**Comment by samruddhi-Rahegaonkar** [comment]
@nope3472 Everywhere There is a Error Handling in the code and it disconnects after write.

**Comment by samruddhi-Rahegaonkar** [comment]
@hpdang This one is also good to merge.
