### PR TITLE
fix: Refactored badge message provider

### LINKED ISSUE #1399: Refactor BadgeMessageProvider into smaller, maintainable files
BadgeMessageProvider has grown insanely around 1041 lines all the custom animation stuff is in it.
Please refactor the BadgeMessageProvider and make seperate utility for custom animations.

### PR DESCRIPTION
**Pull request by nope3472**
Fixes #1399

## Changes 
-Refactored BadgeMessageProvider to keep the file clean and focused 
- Improves code readability and maintainability 

## Screenshots / Recordings  

**Checklist**: 
- [ ] **No hard coding**: I have used resources from `constants.dart` without hard coding any value.
- [ ] **No end of file edits**: No modifications done at end of resource files.
- [ ] **Code reformatting**: I have reformatted code and fixed indentation in every file included in this pull request.
- [ ] **Code analyzation**: My code passes analyzations run in _flutter analyze_ and tests run in _flutter test_.

### CODE REVIEW

File: lib/providers/badge_message_provider.dart [hunk 1]
```diff
@@ -10,19 +9,12 @@ import 'package:badgemagic/bademagic_module/models/data.dart';
...
-import 'package:badgemagic/badge_animation/ani_diamond.dart';
-import 'package:badgemagic/badge_animation/ani_cupid.dart';
-import 'package:badgemagic/badge_animation/ani_feet.dart';
-import 'package:badgemagic/badge_animation/ani_diagonal.dart';
-import 'package:badgemagic/badge_animation/ani_emergency.dart';
-import 'package:badgemagic/badge_animation/ani_beating_hearts.dart';
-import 'package:badgemagic/badge_animation/ani_fireworks.dart';
+import 'package:badgemagic/utils/custom_animation_transfers.dart';
 
 Map<int, Mode> modeValueMap = {
```
Comment (samruddhi-Rahegaonkar) [inline lib/providers/badge_message_provider.dart:21]: I think you again did the wrong mappings.

**Review by samruddhi-Rahegaonkar — CHANGES_REQUESTED** [review]

**Comment by nope3472** [comment]
@samruddhi-Rahegaonkar once the mapping_fix pr gets merged then i will update this branch

**Comment by samruddhi-Rahegaonkar** [comment]
@nope3472 Resolve conficts Please.

**Comment by samruddhi-Rahegaonkar** [comment]
@nope3472 The PR has already get mereged Please do the needful.

**Comment by nope3472** [comment]
hey @mariobehling  @hpdang i think we can go ahead with this pr

**Comment by mariobehling** [comment]
@sourcery-ai review

**Comment by SourceryAI** [comment]
Hi @mariobehling! 👋

Only authors and team members can run @sourcery-ai commands on public repos.

If you are a team member, install the [@sourcery-ai bot](https://github.com/apps/sourcery-ai/installations/new) to get access ✨

**Comment by techyay** [comment]
@sourcery-ai review

**Comment by SourceryAI** [comment]
Hi @techyay! 👋

Only authors and team members can run @sourcery-ai commands on public repos.

If you are a team member, install the [@sourcery-ai bot](https://github.com/apps/sourcery-ai/installations/new) to get access ✨

**Review by mariobehling — CHANGES_REQUESTED** [review]
Please resolve conflicts.

**Comment by hpdang** [comment]
@nope3472 please update this today so we can move on

**Review by samruddhi-Rahegaonkar — APPROVED** [review]

**Comment by nope3472** [comment]
@hpdang updated the branch

**Comment by hpdang** [comment]
@nope3472 still showing branch is out of date

**Comment by nope3472** [comment]
@hpdang i have again updated the branch

File: lib/utils/custom_animation_transfers.dart [hunk 2]
```diff
@@ -0,0 +1,901 @@
...
+      mode: Mode.fixed,
+      speed: selectedSpeed,
+      flash: false,
+      marquee: false,
+    ));
+  }
+
+  Data data = Data(messages: equalizerFrames);
+  DataTransferManager manager = DataTransferManager(data);
+  await transferData(manager);
```
Comment (CloudyPadmal) [inline lib/utils/custom_animation_transfers.dart]: This doesn't have a try/catch as the others.

**Comment by CloudyPadmal** [comment]
I'm wondering if this is the right way to solve the issue pointed out in #1399.

#1399 states that the file has grown too large. However, this PR just exports each function into a separate file, and that file is also similar in length.

What if we instead created several small files, all inside a separate subdirectory for each animation type?

@nope3472 @samruddhi-Rahegaonkar

**Comment by samruddhi-Rahegaonkar** [comment]
> I'm wondering if this is the right way to solve the issue pointed out in #1399.
> 
> #1399 states that the file has grown too large. However, this PR just exports each function into a separate file, and that file is also similar in length.
> 
> What if we instead created several small files, all inside a separate subdirectory for each animation type?
> 
> @nope3472 @samruddhi-Rahegaonkar

@CloudyPadmal I do agree with it.

**Comment by nope3472** [comment]
hey @CloudyPadmal thanks for the suggestion i have made the requested changes

File: lib/utils/custom_animation_transfers.dart (hunk 2 above)
Comment (nope3472) [reply lib/utils/custom_animation_transfers.dart]: added

**Comment by nope3472** [comment]
@mariobehling @hpdang @samruddhi-Rahegaonkar i think we can go with this one

**Comment by hpdang** [comment]
@CloudyPadmal could you please help to check this?

**Comment by samruddhi-Rahegaonkar** [comment]
@hpdang Looks good to me!

**Review by samruddhi-Rahegaonkar — APPROVED** [review]

**Comment by nope3472** [comment]
@mariobehling i have resolved the conflicts here also

**Review by CloudyPadmal — APPROVED** [review]
