### PR TITLE
fix: multiple bluetooth dialogs on rotation 

### LINKED ISSUE #101: Multiple bluetooth dialogs being created on rotation
**Describe the bug**

The AlertDialog asking for bluetooth permission is being recreated on rotation of the device.

**To Reproduce**

1 Open the app
2 Bluetooth alert dialog pops up
2 Rotate the device
3 Dismiss a dialog
4 An AlertDialog is still present

**Expected behavior**

Only one dialog should be present

**Logs**

**Screenshots**

ezgif com-video-to-gif

**Smartphone Info:**
|               | |
|---------------|-|
|Device         |Nokia 6.1 Plus|
|Android Version| Pie 9.0    |

**Additional context**

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #101 

Changes: 
- we lock the screen rotation before the intent starts
- we unlock the screen rotation when intent is complete

Additional Context
This bug has been since android 2.2 ( https://issuetracker.google.com/issues/37114831 ). This is a workaround until the android team fixes it

### CODE REVIEW

**Comment by adityastic** [comment]
@iamareebjamal Please Review

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt [hunk 1]
```diff
@@ -190,6 +190,7 @@ class MessageActivity : AppCompatActivity() {
 
     override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
         if (requestCode == REQUEST_ENABLE_BT) {
+            this.requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Why?

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Because Sir, whenever the user interacts with the dialog. We need to enable the ability to rotate the device

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Else the orientation will remain locked

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: I have not seen this in any other Android App

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: @iamareebjamal. This is the best option I can think of, Locking the orientation until the dialog is gone. Please have a look at the original issue, I have shared the link in the PR. We cannot solve it without android fixing it themselves

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: @iamareebjamal we might have done something innovative 😅

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: First ask yourself why are multiple dialogs being created?

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Sir. So, ACTION_REQUEST_ENABLE is a system intent. It shows a system activity that allows the user to turn on Bluetooth. This system activity class is an instance of  RequestPermissionHelperActivity. And unfortunately this instance gets recreated on rotation

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: @iamareebjamal, we cannot fix this issue without changing the code in com.android.settings.bluetooth.RequesPermissionHelperActivity and that is not possible

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: This issue is to be fixed by the Android team in Google, but unfortunately it is not

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Therefore to avoid the creation of multiple instances of the RequestPermissionHelperActivity we lock the screen orientation before starting the system intent and unlock the screen orientation when the RequestPermissionHelperActivity returns back to our application

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: @iamareebjamal This is what the issue is according to me

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Or, the activity gets recreated on rotation and you request Android to show the dialog?

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: @iamareebjamal Sir the activity does recreate on rotation. But the activity we are talking about right now is launched from the Bluetooth Adapter intent

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: There is an issue with the system activity that it does not handle rotation and it recreates the activity itself and stacks on top of each other

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Check this screenshot, notice the activity name at the top. It shows you the current activity as 

"com.android.settings.bluetooth.RequestPermissionHelperActivity"

This is a system activity and we cannot control this activity sir, not possible for any app to control a system activity.
gg

Therefore when we start launching this activity, we lock the current orientation and as soon as this activity returns back to our app, we unlock the rotation. Sorry if I confused you

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: So sir, we need to make changes in the onSaveInstanceState() and onRestoreInstanceState() in 'com.android.settings.bluetooth.RequestPermissionHelperActivity' which is not possible

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: @iamareebjamal any lead on this sir?

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Can you show me a stack overflow question or any other source of what you are saying?

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Yes sure sir

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: @iamareebjamal https://stackoverflow.com/questions/4873564/bluetooth-activation-alert-dialog-multiplication-after-screen-rotation

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: If you need anything else. Let me know
