### PR TITLE
fix: retain fragment info when orientation changed

### LINKED ISSUE #431: Text in edit screen disappears on turning phone to widescreen
When I edit the screen and I turn the phone the text disappears.

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #431 

Changes: 
- improved naming scheme for viewmodel
- fragment should share viewmodel

Screenshots for the change:

### CODE REVIEW

File: app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt [hunk 1]
```diff
@@ -74,7 +74,7 @@ class TextArtFragment : BaseFragment() {
     private val drawableRecyclerAdapter = DrawableAdapter()
     private val modeAdapter = ModeAdapter()
 
-    private val viewModel by viewModel<TextArtViewModel>()
+    private val textArtViewModel by sharedViewModel<TextArtViewModel>()
```
Comment (iamareebjamal) [inline app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt]: Revert name to viewModel

Comment (adityastic) [reply app/src/main/java/org/fossasia/badgemagic/ui/fragments/TextArtFragment.kt]: ready to merge
