### PR TITLE
fix: save state of preview badge, updated sdk's in build gradle to the latest available

### LINKED ISSUE #148: Preview does not hold its state when screen is rotated
**Describe the bug**
When the screen is rotated, the Badge Preview does not hold its state anymore

**Screenshots**
ss0
When Screen rotated:
ss1

**Would you like to work on the issue?**
Yep

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #148
Changes: 
- Added a singleton class to hold the state values when the events onSaveInstanceState and onRestoreInstanceState are fired

Screenshots for the change:
tt0
tt1

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @anhanh11001 @yatri1609 Please Peer Review

**Comment by adityastic** [comment]
@iamareebjamal Please Have a look

**Comment by iamareebjamal** [comment]
I thought this was made in a fragment, but it is not. So you can't and shouldn't use ViewModel

Use the bundle, not a singleton

Using a singleton means you cannot have more than one preview widget in the entire app

**Comment by iamareebjamal** [comment]
Much simpler would be to persist state in Fragment and ViewModel and just set the saved drawable to widget on rotation

**Comment by adityastic** [comment]
Alright, @iamareebjamal I did think about using Parcelable. But, Let me get the fragments up and running, and fix it the way you suggested

**Comment by adityastic** [comment]
@iamareebjamal I'll consider the bundle's currently. Will shift it to fragments later

**Comment by adityastic** [comment]
@iamareebjamal I cannot push this right now. Please check the other pull requests, else the merge will create other issues. If you check those pr and wish to merge them, I would love to update it there after

**Comment by adityastic** [comment]
@iamareebjamal check now. Using bundles, safe and sober as you suggested

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt [hunk 1]
```diff
@@ -2,6 +2,4 @@ package com.nilhcem.blenamebadge.ui.badge_preview
 
 import android.graphics.Rect
 
-internal class Cell {
-    var list = mutableListOf<Rect>()
-}
+data class Cell(var list: MutableList<Rect> = mutableListOf())
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt]:
```suggestion
data class Cell(val list: List<Rect> = mutableListOf())
```

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt [hunk 2]
```diff
@@ -1,5 +1,30 @@
 package com.nilhcem.blenamebadge.ui.badge_preview
 
-internal class CheckList {
+import android.os.Parcel
+import android.os.Parcelable
+
+internal class CheckList() : Parcelable {
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt]: You can use Parcelize

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt]: And make this a data class

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt [hunk 3]
```diff
@@ -82,6 +84,51 @@ class PreviewBadge : View {
...
+            Mode.RIGHT -> 2
+            Mode.UP -> 3
+            Mode.DOWN -> 4
+            Mode.FIXED -> 5
+            Mode.SNOWFLAKE -> 6
+            Mode.PICTURE -> 7
+            Mode.ANIMATION -> 8
+            Mode.LASER -> 9
+        })
+        bundle.putParcelableArrayList("checkList", ArrayList(this.checkList))
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: Use putParcelable

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: putParcelable wont work for Lists sir

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt (hunk 1 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt]: need to add things to the list, cant use list

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt (hunk 2 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt]: Done

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt (hunk 3 above)
Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: Why you want to store list of checklist?

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt [hunk 4]
```diff
@@ -82,6 +84,51 @@ class PreviewBadge : View {
                 View.MeasureSpec.makeMeasureSpec(calculatedHeight, View.MeasureSpec.EXACTLY))
     }
 
+    public override fun onSaveInstanceState(): Parcelable? {
+        val bundle = Bundle()
+        bundle.putParcelable("superState", super.onSaveInstanceState())
+        bundle.putBoolean("ifFlash", this.ifFlash)
+        bundle.putBoolean("ifMarquee", this.ifMarquee)
+        bundle.putInt("badgeSpeed", this.badgeSpeed)
+        bundle.putInt("badgeMode", when (badgeMode) {
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: put string and use enum value of to deserialize

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt (hunk 3 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: To check them with the cells when working with animations

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt (hunk 4 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: Let me use ordinal, it would be better and more memory efficient

**Comment by adityastic** [comment]
@iamareebjamal Have a look

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt (hunk 3 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: The Animations work by having two 2d lists, we have one as the base and another which checks if the index of the list has true or false, which makes the led glow. So, to create these animations we just play with the indexes of the lists, using some simple math operations the animations appear like they currently are

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: I'll repeat, Why you want to store list of checklist and not just checklist? It makes no sense to put it in ArrayList and save in bundle

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt [hunk 5]
```diff
@@ -1,5 +1,7 @@
 package com.nilhcem.blenamebadge.ui.badge_preview
 
-internal class CheckList {
-    var list = mutableListOf<Boolean>()
-}
+import android.os.Parcelable
+import kotlinx.android.parcel.Parcelize
+
+@Parcelize
+data class CheckList(var list: MutableList<Boolean> = mutableListOf()) : Parcelable
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt]:
```suggestion
data class CheckList(var list: List<Boolean> = mutableListOf()) : Parcelable
```

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt (hunk 1 above)
Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt]: You can

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt (hunk 3 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: @iamareebjamal Checklist contains a single list, we need a 2d list for the x and y coordinates. Therefore, a list of checklists

And we want to save it because it stores the binary values in the boolean of the the drawable or text

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt (hunk 1 above)
Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt]: And please don't resolve conversations, I'm going to have to stop reviewing your PRs if you resolve conversations manually. It is extremely annoying

Leave them open if you are not going to do it

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt [hunk 6]
```diff
@@ -82,6 +84,30 @@ class PreviewBadge : View {
                 View.MeasureSpec.makeMeasureSpec(calculatedHeight, View.MeasureSpec.EXACTLY))
     }
 
+    public override fun onSaveInstanceState(): Parcelable? {
+        val bundle = Bundle()
+        bundle.putParcelable("superState", super.onSaveInstanceState())
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: Make keys constants

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt (hunk 5 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt]: Sir, values are being added inside the checklist, List will not allow me to add values to it. Only mutable lists allow me to perform add operations

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt (hunk 6 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: On it

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt (hunk 3 above)
Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: `bundle.putParcelableArrayList("checkList", this.checkList)`

Why can't you write this?

You are storing checkList after wrapping in ArrayList, and while restoring, you just assign

```
this.checkList = bundle.getParcelableList
```

Makes absolutely no sense to me. Either wrap and extract in both places or wrap nowhere

**Comment by iamareebjamal** [comment]
Whenever you create a PR, always check Allow edits from maintainers

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt (hunk 5 above)
Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt]: OK, this is Kotlin List, not Java, so just write `var list = mutableListOf<Boolean>()`

**Comment by adityastic** [comment]
> Whenever you create a PR, always check Allow edits from maintainers
I did not change anything sir. It is checked already

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt (hunk 5 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt]: Ok sir

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt]: @iamareebjamal Sir, It says 'A type annotation is required on a value parameter' when I change it to `var list = mutableListOf<Boolean>()`

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt (hunk 1 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt]: @iamareebjamal I did not resolve it sir, it got resolved automatically when I clicked the commit suggestion button

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt (hunk 5 above)
Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/CheckList.kt]: OK, let it be. My mistake, I did not realize it was Kotlin built in type and not java interface List

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt (hunk 1 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/Cell.kt]: Sir, It says 'A type annotation is required on a value parameter'

**Comment by iamareebjamal** [comment]
Just remove ArrayList wrapping checkList, rest looks good

**Comment by adityastic** [comment]
> Just remove ArrayList wrapping checkList, rest looks good

Yes Sir, give me a minute

**Comment by adityastic** [comment]
@iamareebjamal Please check the other PR which fixes the animations as well sir. By the time, I will get this fixed

**Comment by adityastic** [comment]
@iamareebjamal done sir, have a look.

File: app/build.gradle [hunk 7]
```diff
@@ -3,18 +3,22 @@ plugins {
...
 android {
-    compileSdkVersion 27
+    compileSdkVersion 28
     buildToolsVersion '28.0.3'
 
     defaultConfig {
         applicationId 'com.nilhcem.blenamebadge'
-        minSdkVersion 18
-        targetSdkVersion 27
+        minSdkVersion 21
```
Comment (iamareebjamal) [inline app/build.gradle]: Why?

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt [hunk 8]
```diff
@@ -82,6 +92,30 @@ class PreviewBadge : View {
...
     }
 
+    public override fun onSaveInstanceState(): Parcelable? {
+        val bundle = Bundle()
+        bundle.putParcelable(BUNDLE_STATE, super.onSaveInstanceState())
+        bundle.putBoolean(BUNDLE_FLASH, this.ifFlash)
+        bundle.putBoolean(BUNDLE_MARQUEE, this.ifMarquee)
+        bundle.putInt(BUNDLE_SPEED, this.badgeSpeed)
+        bundle.putInt(BUNDLE_MODE, this.badgeMode.ordinal)
+        bundle.putParcelableArrayList(BUNDLE_CHECKLIST, ArrayList(this.checkList))
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]:
```suggestion
        bundle.putParcelableArrayList(BUNDLE_CHECKLIST, this.checkList)
```

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: I tried that sir, did not work. It only takes arraylist as an argument

File: app/build.gradle (hunk 7 above)
Comment (adityastic) [reply app/build.gradle]: most of the devices are lollipop+. should I revert it back to 18 ?

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt (hunk 8 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: and there was no function for lists or mutable lists

Comment (iamareebjamal) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: Then change checkList to ArrayList

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: Alright Sir

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: Done @iamareebjamal

File: app/build.gradle (hunk 7 above)
Comment (iamareebjamal) [reply app/build.gradle]: Because we don't use any API that is only available in API 21+, why deliberately increase minSdk when there is no need?

**Comment by iamareebjamal** [comment]
Build failing

**Comment by adityastic** [comment]
> Build failing

Just a min, Removed Vector Drawable Support

**Comment by adityastic** [comment]
@iamareebjamal should work now

**Comment by adityastic** [comment]
@iamareebjamal Done, Built successfully
