### PR TITLE
fix: Made keyboard appear automatically when shifting to text mode.

### LINKED ISSUE #109: Keyboard should go down on pressing the enter button on keyboard.
**Describe the bug**
When the enter button is pressed on the keyboard, no action takes place and the keyboard stays up.

**Expected behavior**
The keyboard should go down.

**Additional context**
@iamareebjamal should it be made such that when the keyboard enter button is pressed, the preview starts appearing on the preview badge?

**Would you like to work on the issue?**

YES.

### LINKED ISSUE #186: Keyboard does not pop up automatically when shifting to text mode.
**Describe the bug**
On shifting from drawble to text mode, keyboard does not pop up automatically.

**Expected behavior**
Keyboard should pop up automatically.

**Would you like to work on the issue?**

YES.

### PR DESCRIPTION
**Pull request by yashk2000**
Fixes #186 
Fixes #109
 
Changes: Keyboard now pops up automatically when shifting to text mode.

### CODE REVIEW

**Comment by yashk2000** [comment]
@iamareebjamal  @adityastic please review.

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt [hunk 1]
```diff
@@ -146,6 +146,10 @@ class MessageActivity : AppCompatActivity() {
                 }
 
                 R.id.textRadio -> {
+                    val inputManager: InputMethodManager = this.getSystemService(Context.INPUT_METHOD_SERVICE)
+                            as InputMethodManager
+                    inputManager.showSoftInput(content, 1)
```
Comment (adityastic) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: Never use integers as the second parameter. Rather use InputMethodManager.SHOW_IMPLICIT Which is a constant of InputMethodManager. But as you want to force the keyboard, use InputMethodManager.SHOW_FORCED

**Comment by adityastic** [comment]
@yashk2000 can you tell me hoe #109 is fixed?. I don't see the code to hide the keyboard on enter

File: app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt (hunk 1 above)
Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: also, instance of inputmanager is being create 3 times inside MessageActivity.kt , just define it  outside instead of intializing it in every scope

Comment (yashk2000) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/message/MessageActivity.kt]: I'll make these changes.

**Comment by yashk2000** [comment]
@adityastic I have made the changes.

**Comment by adityastic** [comment]
@iamareebjamal please review

**Comment by yashk2000** [comment]
@iamareebjamal please review.

File: app/src/main/java/com/nilhcem/blenamebadge/util/Utils.kt [hunk 2]
```diff
@@ -0,0 +1,20 @@
+package com.nilhcem.blenamebadge.util
+
+import android.content.Context
+import android.view.View
+import android.view.inputmethod.InputMethodManager
+
+object Utils {
```
Comment (iamareebjamal) [inline app/src/main/java/com/nilhcem/blenamebadge/util/Utils.kt]: KeyboardUtils

**Comment by yashk2000** [comment]
@iamareebjamal changes made. Please review.
