### PR TITLE
fix: maintaining ratio logic and some fixes in preview badge

### LINKED ISSUE #126: App not working in android Lollipop 5.1
**Describe the bug**
App crashes as soon as it starts.

**To Reproduce**
Try to launch the app in Android 5.1.

**Expected behavior**
App should run without crash.

**Logs**
```
java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:810)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:789)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:756)
        at android.graphics.drawable.VectorDrawable$VectorDrawableState.createCachedBitmapIfNeeded(VectorDrawable.java:713)
        at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
        at com.nilhcem.blenamebadge.ui.badge_preview.PreviewBadge.onDraw(PreviewBadge.kt:225)
        at android.view.View.draw(View.java:15495)
        at android.view.View.updateDisplayListIfDirty(View.java:14384)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3516)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3495)
        at android.view.View.updateDisplayListIfDirty(View.java:14334)
        at android.view.View.getDisplayList(View.java:14413)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:295)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:335)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2940)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2754)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2368)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1293)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6599)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:800)
        at android.view.Choreographer.doCallbacks(Choreographer.java:603)
        at android.view.Choreographer.doFrame(Choreographer.java:572)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:786)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

**Smartphone Info:**

|                  | |
|---------------|-|
|Device              | Intex Cloud Flash|
|Android Version| Lollipop 5.1    |

**Would you like to work on the issue?**

No.

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #126 

Changes: 
- onMeasure now calculates the height according to the width, irrespective of the originalHeight ( This fixes the Lollipop and below API issue as onMeasure use to return heightMeasuredSpec as 0)
- offsetToAdd should be different than the global offset for the widget as it usually did not make the cells in the center of the widget.

Screenshots for the change:
Screenshot 2019-04-03 at 4 32 58 PM

### CODE REVIEW

**Comment by adityastic** [comment]
@yashk2000 @yatri1609 @naman653 Please Peer Review

**Comment by adityastic** [comment]
@iamareebjamal or sir you can directly review it

File: app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt [hunk 1]
```diff
@@ -102,19 +91,22 @@ class PreviewBadge : View {
...
-                        top + (offset * 2) + i * singleCell + singleCell
+                        left + (offsetXToAdd * 2) + j * singleCell,
+                        top + (offsetXToAdd * 2) + i * singleCell,
+                        left + (offsetXToAdd * 2) + j * singleCell + singleCell,
+                        top + (offsetXToAdd * 2) + i * singleCell + singleCell
                 ))
             }
         }
-        bgBounds = RectF((left + offset).toFloat(), (top + offset).toFloat(), (right - offset).toFloat(), ((singleCell * badgeHeight) + (offset * 3)).toFloat())
+
```
Comment (yashk2000) [inline app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: Please remove the extra line.

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: On It

Comment (adityastic) [reply app/src/main/java/com/nilhcem/blenamebadge/ui/badge_preview/PreviewBadge.kt]: Done @yashk2000

**Comment by adityastic** [comment]
@iamareebjamal have a look
